"use client";

import Image from "next/image";
import { useState } from "react";
import { Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { track } from "@/lib/analytics/client";

/**
 * Preview of the server-rendered PNG card, plus the download action. The PNG
 * itself is generated by /api/share-card/[id] so it's identical everywhere.
 */
export function ShareCard({ sessionId, score }: { sessionId: string; score: number }) {
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const src = `/api/share-card/${sessionId}`;

  const download = async () => {
    setDownloading(true);
    setError(null);
    try {
      const response = await fetch(src);
      if (!response.ok) throw new Error("card unavailable");
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `roastme-ai-${score}-100.png`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
      track("share_card_downloaded", {}, sessionId);
    } catch {
      setError("The card didn't generate. Try again in a second.");
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="overflow-hidden rounded-2xl border border-edge bg-ink-soft">
        <Image
          src={src}
          alt={`RoastMe AI share card — ${score} out of 100`}
          width={1200}
          height={630}
          className="h-auto w-full"
          unoptimized
        />
      </div>

      <Button variant="secondary" size="lg" className="w-full" disabled={downloading} onClick={download}>
        {downloading ? <Loader2 className="size-5 animate-spin" /> : <Download className="size-5" />}
        Download Roast Card
      </Button>

      {error ? <p className="text-sm text-ember">{error}</p> : null}
    </div>
  );
}
